### ISSUE TITLE
python3 pyg2p COSMO

### ISSUE THREAD

**Issue by domeniconappo** [ec-jrc/pyg2p#1]
https://github.com/ec-jrc/pyg2p/tree/20-py3

Tests on branch 20-py3 fails for COSMO files.
Results show correct values (identical to reference data) but with a different mask. Still no clue why it happens.

Actually, new results  seem to be more appropriate/correct, as missing values in COSMO domain are correctly reported while in reference output, values outside COSMO domain are not MV (!).

See attached samples:

![cosmo_1](https://user-images.githubusercontent.com/7078978/70790714-ee166880-1d95-11ea-94ba-ab710aca1437.PNG)
![cosmo_2](https://user-images.githubusercontent.com/7078978/70790715-ef479580-1d95-11ea-8ddf-2d9870184c1c.PNG)

[cosmo_results.zip](https://github.com/ec-jrc/pyg2p/files/3960179/cosmo_results.zip)

**Comment by blazk** [comment]
Hi, I'm also surprised to see it! the second map definitely makes more sense. I'll try to understand what is going on in our system

**Comment by blazk** [comment]
I suspect our COSMO-LEPS interpolation tables must have been generated with incorrect mask (dem.map?)

**Comment by domeniconappo** [comment]
I didn't generated the interpolation table btw: 
I used what you sent to me so that should not be the cause. Maybe you meant that you have an incorrect mask configured for COSMO?

I will try to run same test with current master version and I'll tell you if problem is in the code.

**Comment by blazk** [comment]
ok, I can't remember what I've sent you, all files are deleted on my side :) But that's odd. I don't know where would this pink stuff come from then. Waiting curiously for your master version test results

**Comment by domeniconappo** [comment]
@blazk 

Just switched on master (and installed old grib_api 1.28...)

Run the same commands for COSMO and have same results as the py3 branch (no pink stuff and correct domain with missing values outside).

So that problem is not originated from MV handling in pyg2p...must be DEM/AREA maps on your side. Interpolation table is not the root cause as I use the same for current tests.

Some postprocessing on those maps?

**Comment by domeniconappo** [comment]
[T24a0000.zip](https://github.com/ec-jrc/pyg2p/files/3960472/T24a0000.zip)

**Comment by blazk** [comment]
but which file is the "mask"? is it the @cloneMap parameter? I've checked in our system but all json files are using the same dem.map as cloneMap and it looks correctly:
![image](https://user-images.githubusercontent.com/160080/70804200-c4693b80-1dad-11ea-97e3-378cf35f4902.png)

**Comment by blazk** [comment]
ah yes, it's actually special COS postprocessing:

`
for map in T24a0*.???; do
    # cover the map with minimum temperature
    pcrcalc "$map = if(defined($map), $map, if(defined(dem.map), mapminimum($map)))"
done

for map in E06a0*.??? R06a0*.???; do
    # cover the map with zeros
    pcrcalc "$map = if(defined($map), $map, if(defined(dem.map), 0))"
done
'

**Comment by domeniconappo** [comment]
Super! Spot on. So it's not an error? It's covered on purpose?

**Comment by blazk** [comment]
it looks very on purpose :)

**Comment by blazk** [comment]
Also just wanted you to know that I've switched to this repository instead of Bitbucket one and will not use Bitbucket one anymore

**Comment by domeniconappo** [comment]
Thank you! 
I'm going to delete the bb one
